version: "3.8"

services:
  service:
    build: ./service
    ports:
      - '3000:3000'
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=francis
      - POSTGRES_USER=francis
      - POSTGRES_PASSWORD=francis