version: '3.8'

services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=francis
      - POSTGRES_USER=francis
      - POSTGRES_PASSWORD=francis
  redis:
    image: redis
    ports:
      - '6379:6379'
