name: Push main

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      working-directory: ./service

    steps:
      - uses: actions/checkout@v2

      - name: Use node.js 14.15.3
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.3'

      - name: Setup
        run: npm ci

      - name: Run tests
        run: npm test