name: Test pull request

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: '14.15.3'

      - name: Setup and run tests
        working-directory: ./service
        run: |
          npm ci
          npm test